export const ARTICLE_FROM_BG_TO_NL = {
    folder: '/assets/images/profile/from-bg-to-nl/',
    en: {
        heading: 'From Bulgaria To The Netherlands',
        title: 'From Bulgaria to the Netherlands: How a Fading Middle Class Drives Student Migration',
        author: 'Karina Karagyoz',
        date: 'Sep 28, 2024',
        time: '4 min read',
        para1: 'Bulgaria has the smallest share of the middle class in the European Union, according to recent statistics. The economic challenges in the country have led many young Bulgarians to study and work abroad, with the Netherlands being one of the top destinations. ',
        imgDesc1: 'People walking in Sofia, Bulgaria © Karina Karagyoz',
        para2: 'While the EU average is nearly 60% and leading countries like Slovakia reach 75%, a report shows that Bulgaria has the lowest middle-class representation, with only 51% of its population in this group. The data comes from Eurofound - the EU Agency for the improvement of living and working conditions.',
        para3: 'This economic contrast sheds light on why so many students are looking to study abroad. Limited job opportunities, low investment, and weak institutions - all factors explaining why the middle class is shrinking and students are left with the question: should they stay in Bulgaria or pursue education and career elsewhere?',
        para4: `At the Bulgarian Society Netherlands, we aim to build a supportive community for Bulgarian students. That's why we reached out to students and members of the Bulgarian Society in Amsterdam to hear about their experiences of studying and working in the Netherlands.`,
        para5: `"I knew the Netherlands had a stable economy. I wanted to meet new people and explore different job opportunities," says David Tahor, a student and founder of The Poké Lab restaurants. `,
        para6: `From his experiences in both countries, David shares that high levels of corruption are one of the main causes in the slow decline of the middle class in Bulgaria. `,
        para7: `“Many systems in Bulgaria operate in outdated ways and lack digitization, while in the Netherlands, many services are accessible online, and young people are actively employed in public sector roles,” he further explains. `,
        para8: `“I feel that I belong to Bulgaria,” David says, expressing his desire to return home one day, despite the economic challenges.`,
        para9: `To improve the situation, David believes that education in Bulgaria should focus more on financial competence and encourage interaction with other countries.`,
        para10: `"In the Netherlands, I found my space to grow,” says Ivan Zdravkov, Product Manager at Adidas and a former student in Breda. “Bulgarians are constantly stressed about working more and earning less. On the other side, the Dutch have a different approach and offer flexible work schedules," he adds. `,
        para11: `Like David, Ivan told us how important the public sector in shaping the middle class is. “In the Netherlands, it plays a significant role, but in Bulgaria, public sector workers are often underpaid.”`,
        imgDesc2: `Streets of Groningen © Karina Karagyoz`,
        para12: `“It doesn’t matter where you are in the Netherlands; because there's always something to do, and it's very lively,” Ivan notes on his studies in a small town.  `,
        para13: `He also believes Bulgaria should encourage students to work, suggesting that “the country could offer scholarships for working students, similar to what’s done in the Netherlands.”`,
        para14: `“Studying abroad does not necessarily harm Bulgaria,” Ivan concludes. “In fact, those who return bring valuable experience in their home country.”`,
    },
    bg: {
        heading: 'От България до Нидерландия',
        title: 'От България до Нидерландия: Как намаляващата средна класа увеличава студентската миграция',
        author: 'Карина Карагьоз',
        date: '28 септември 2024',
        time: '4 мин четене',
        para1: 'България е с най-малък дял средна класа в Европейския съюз, сочат последни статистики. Икономическата ситуация в страната принуждава много млади българи да търсят образование и работа в чужбина, а Нидерландия е една от най-предпочитаните дестинации.',
        imgDesc1: 'Хора на разходка в София, България © Карина Карагьоз',
        para3: 'Доклад от Eurofound - Агенция за подобряване на условията на живот и труд - показва, че България има най-ниска средна класа, като само 51% от населението й попада в тази група, докато средно за ЕС процентът е близо 60%, а водещи страни като Словакия достигат 75%.',
        para4: `Този икономически контраст отваря въпроса защо толкова много студенти търсят развитие в чужбина. Ограничените възможности за работа и неефективно работещите институции обясняват както намаляването на средната класа, така и дилемата, пред които стотици млади хора в България се сблъскват: дали да останат в страната си или да продължат образованието и кариерата си в чужбина.`,
        para5: `Ние, от Българското Общество в Нидерландия, се стремим да изградим една подкрепяща общност за българските студенти. Ето защо се свързахме с някои от нашите членове в Амстердам, за да разберем повече за техния опит в обучението и работата в Нидерландия.`,
        para6: `„Знаех, че Нидерландия има стабилна икономика. Исках да се срещна с нови хора и да проуча различните възможности за работа“, казва Давид Тахор, студент и основател на ресторантите The Poké Lab. От богатия си опит и в двете страни, Давид споделя, че високите нива на корупция са една от основните причини за бавния упадък на средната класа в България. `,
        para7: `„Много системи в България работят по остарели начини и им липсва дигитализация, докато в Нидерландия много услуги са достъпни онлайн, а младите хора са наети на длъжности в публичния сектор“, обяснява още той. `,
        para8: `„Чувствам, че все пак принадлежа на България,“ казва Давид, споделяйки желанието си един ден да се върне в България, въпреки икономическите предизвикателства. `,
        para9: `За да се подобри ситуацията, Давид смята, че образованието в България трябва да се фокусира повече върху финансовата компетентност на населението и да насърчава взаимодействието с други страни. `,
        para11: `„В Холандия намерих своето място за развитие“, казва Иван Здравков, продуктов мениджър в Adidas и бивш студент в Бреда. „Българите са постоянно стресирани; те работят повече и печелят по-малко. Докато холандците имат различен подход и предлагат гъвкава работна среда“, добавя той. `,
        para10: `Подобно на Давид, Иван споделя колко важен е публичният сектор за формирането на средната класа. „В Холандия този сектор играе значителна роля, но в България служителите са ниско платени.“`,
        imgDesc2: `Улиците на Гронинген © Карина Карагьоз`,
        para12: `„Няма значение къде се намирате в Холандия; защото винаги има какво да се прави и е много живо”, отбелязва Иван за следването си в малкия град Бреда. `,
        para13: `Той също така смята, че България трябва да насърчава студентите да работят, като предлага „страната да дава стипендии на работещи студенти, подобно на това, което се прави в Холандия“. `,
        para14: `„Ученето в чужбина не вреди непременно на България“, заключава Иван. „Всъщност тези, които се връщат обратно, носят ценен опит в страната ни.“`,
    },
}