export const EUROPEAN_COUNTRIES = [
  { country: "Albania", iso2: "AL", iso3: "ALB", phoneCode: "+355" },
  { country: "Andorra", iso2: "AD", iso3: "AND", phoneCode: "+376" },
  { country: "Armenia", iso2: "AM", iso3: "ARM", phoneCode: "+374" },
  { country: "Austria", iso2: "AT", iso3: "AUT", phoneCode: "+43" },
  { country: "Azerbaijan", iso2: "AZ", iso3: "AZE", phoneCode: "+994" },
  { country: "Belarus", iso2: "BY", iso3: "BLR", phoneCode: "+375" },
  { country: "Belgium", iso2: "BE", iso3: "BEL", phoneCode: "+32" },
  {
    country: "Bosnia and Herzegovina",
    iso2: "BA",
    iso3: "BIH",
    phoneCode: "+387",
  },
  { country: "Bulgaria", iso2: "BG", iso3: "BGR", phoneCode: "+359" },
  { country: "Croatia", iso2: "HR", iso3: "HRV", phoneCode: "+385" },
  { country: "Cyprus", iso2: "CY", iso3: "CYP", phoneCode: "+357" },
  { country: "Czech Republic", iso2: "CZ", iso3: "CZE", phoneCode: "+420" },
  { country: "Denmark", iso2: "DK", iso3: "DNK", phoneCode: "+45" },
  { country: "Estonia", iso2: "EE", iso3: "EST", phoneCode: "+372" },
  { country: "Finland", iso2: "FI", iso3: "FIN", phoneCode: "+358" },
  { country: "France", iso2: "FR", iso3: "FRA", phoneCode: "+33" },
  { country: "Georgia", iso2: "GE", iso3: "GEO", phoneCode: "+995" },
  { country: "Germany", iso2: "DE", iso3: "DEU", phoneCode: "+49" },
  { country: "Greece", iso2: "GR", iso3: "GRC", phoneCode: "+30" },
  { country: "Hungary", iso2: "HU", iso3: "HUN", phoneCode: "+36" },
  { country: "Iceland", iso2: "IS", iso3: "ISL", phoneCode: "+354" },
  { country: "Ireland", iso2: "IE", iso3: "IRL", phoneCode: "+353" },
  { country: "Italy", iso2: "IT", iso3: "ITA", phoneCode: "+39" },
  { country: "Kazakhstan", iso2: "KZ", iso3: "KAZ", phoneCode: "+7" },
  { country: "Kosovo", iso2: "XK", iso3: "UNK", phoneCode: "+383" },
  { country: "Latvia", iso2: "LV", iso3: "LVA", phoneCode: "+371" },
  { country: "Liechtenstein", iso2: "LI", iso3: "LIE", phoneCode: "+423" },
  { country: "Lithuania", iso2: "LT", iso3: "LTU", phoneCode: "+370" },
  { country: "Luxembourg", iso2: "LU", iso3: "LUX", phoneCode: "+352" },
  { country: "Malta", iso2: "MT", iso3: "MLT", phoneCode: "+356" },
  { country: "Moldova", iso2: "MD", iso3: "MDA", phoneCode: "+373" },
  { country: "Monaco", iso2: "MC", iso3: "MCO", phoneCode: "+377" },
  { country: "Montenegro", iso2: "ME", iso3: "MNE", phoneCode: "+382" },
  { country: "Netherlands", iso2: "NL", iso3: "NLD", phoneCode: "+31" },
  { country: "North Macedonia", iso2: "MK", iso3: "MKD", phoneCode: "+389" },
  { country: "Norway", iso2: "NO", iso3: "NOR", phoneCode: "+47" },
  { country: "Poland", iso2: "PL", iso3: "POL", phoneCode: "+48" },
  { country: "Portugal", iso2: "PT", iso3: "PRT", phoneCode: "+351" },
  { country: "Romania", iso2: "RO", iso3: "ROU", phoneCode: "+40" },
  { country: "Russia", iso2: "RU", iso3: "RUS", phoneCode: "+7" },
  { country: "San Marino", iso2: "SM", iso3: "SMR", phoneCode: "+378" },
  { country: "Serbia", iso2: "RS", iso3: "SRB", phoneCode: "+381" },
  { country: "Slovakia", iso2: "SK", iso3: "SVK", phoneCode: "+421" },
  { country: "Slovenia", iso2: "SI", iso3: "SVN", phoneCode: "+386" },
  { country: "Spain", iso2: "ES", iso3: "ESP", phoneCode: "+34" },
  { country: "Sweden", iso2: "SE", iso3: "SWE", phoneCode: "+46" },
  { country: "Switzerland", iso2: "CH", iso3: "CHE", phoneCode: "+41" },
  { country: "Turkey", iso2: "TR", iso3: "TUR", phoneCode: "+90" },
  { country: "Ukraine", iso2: "UA", iso3: "UKR", phoneCode: "+380" },
  { country: "United Kingdom", iso2: "GB", iso3: "GBR", phoneCode: "+44" },
  { country: "Vatican City", iso2: "VA", iso3: "VAT", phoneCode: "+379" },
];

export const PHONE_CODES = [
  "+355", "+376", "+374", "+43", "+994", "+375", "+32", "+387", "+359", "+385", 
  "+357", "+420", "+45", "+372", "+358", "+33", "+995", "+49", "+30", "+36", 
  "+354", "+353", "+39", "+7", "+383", "+371", "+423", "+370", "+352", "+356", 
  "+373", "+377", "+382", "+31", "+389", "+47", "+48", "+351", "+40", "+7", 
  "+378", "+381", "+421", "+386", "+34", "+46", "+41", "+90", "+380", "+44", 
  "+379"
];