export const INTERNSHIPS_LIST = [
  {
    logo: "https://big4accountingfirms.com/wp-content/uploads/Deloitte.svg.png",
    company: "Deloitte",
    specialty: "Summer Business Camp",
    location: "Sofia, Bulgaria",
    label: "Bulgarian",
    duration: "16 - 27 June 2025",
    description:
      "A two-week internship program where participants explore business fields like audit, finance, tax, legal, consulting, and advisory through workshops, case studies, and networking with industry professionals.",
    bonuses:
      "Certificate of completion, networking opportunities, potential for a permanent employment offer.",
    requirements:
      "Second-year university students or above, fluent in Bulgarian and English, curious and eager to learn, available in Sofia for the internship duration.",
    languages: "Bulgarian, English",
    contactMail: "",
    applyLink:
      "https://apply.deloittece.com/en_US/careers/ApplicationMethods?jobId=16533",
    website:
      "https://apply.deloittece.com/en_US/careers/JobDetail/Summer-Business-Camp/16533",
  },
  {
    logo: "",
    company: "Acady",
    specialty: "Internships (see roles on the site)",
    location: "Hybrid / Remote | Netherlands",
    label: "International & Remote",
    duration: "3–6 months (flexible)",
    description:
      "Join Acady and contribute across marketing, operations and product support. Work in a fast-moving environment and help scale impactful initiatives.",
    bonuses: "Hands-on experience, mentorship, flexible schedule",
    requirements:
      "Motivated student or recent graduate with strong communication and organizational skills",
    languages: "English (Dutch is a plus)",
    contactMail: "",
    website: "https://acady.nl/join-our-team",
  },
  {
    logo: "",
    company: "Pepperminds",
    specialty: "Face-to-Face Fundraising Ambassador",
    location: "On-site | Netherlands (multiple cities)",
    label: "International & Remote",
    duration: "Part-time / Flexible",
    description:
      "Work with a fun team to recruit face-to-face ambassadors for leading brands and charities such as CliniClowns, Staatsloterij, KIKA, Rode Kruis, UNICEF and KWF. Flexible shifts and strong growth opportunities.",
    bonuses:
      "Attractive base + bonus structure; average €150–€250 per shift; recruitment bonuses up to €300; masterclasses and events",
    requirements:
      "Communicative, proactive, and eager to develop sales skills; flexible availability; 16+",
    languages: "Dutch, English",
    contactMail: "werken@pepperminds.nl",
    website:
      "https://www.pepperminds.nl/makeithappen/?mkt=LZ&utm_source=viavia&utm_medium=crewapp&utm_campaign=makeithappen",
  },
  {
    logo: "https://neterra.net/images/upload/brands/logo-neterra_1.svg",
    company: "Neterra",
    specialty: "Junior Product Intern",
    location: "Sofia, Bulgaria / Hybrid",
    label: "Bulgarian",
    duration: "3/6 months",
    description:
      "As a Product Intern, you will play a key role in driving our quantitative and market analysis efforts. You’ll work closely with experienced professionals in a collaborative environment where your contributions will make a real impact",
    bonuses: "Meaningful, hands-on experience, ",
    requirements:
      "TBD, depending on your skillset and background, diverse team in a global company and an opportunity for career advancement ",
    languages: "Bulgarian, English",
    contactMail: "cv@neterra.net",
    website: "https://neterra.net/",
  },
  {
    logo: "https://www.pwc.bg/etc.clientlibs/pwc/clientlibs/rebrand-clientlibs/components-colors/resources/images/slim-header-v2/PwC-logo.svg",
    company: "PwC Bulgaria",
    specialty: "Junior Sustainability Audit Analyst",
    location: "Sofia, Bulgaria",
    label: "Bulgarian",
    duration: "Full-time",
    description:
      "Conduct financial and sustainability audits for the largest companies in Europe, ensuring compliance with ESRS, IFRS, and other reporting standards.",
    bonuses:
      "Experience in sustainability auditing and exposure to major European corporations.",
    requirements:
      "Degree in Accounting, Finance, Sustainability, or related field, Strong analytical and problem-solving abilities, Excellent communication and teamwork skills",
    languages: "Bulgarian, English",
    contactMail: "bg_pwc@pwc.com",
    website:
      "https://jobs-cee.pwc.com/ce/en/job/589706WD/Junior-Consultant-in-Audit-Finance",
  },
  {
    logo: "https://www.bgstart.nl/bg/wp-content/uploads/2019/01/favicon.png",
    company: "BG Start",
    specialty: "Accountancy",
    location: "Amsterdam (Hybrid)",
    label: "International & Remote",
    duration: "Flexible",
    description: `Assisting with data entry, processing, and recording transactions. Financial Reporting: Helping prepare financial reports, budgets, and invoices. Administrative Support: Assisting with audits, fact-checking, and maintaining financial documents.`,
    bonuses: "Experience & networking, Valuable mentoring opportunities",
    requirements: "Accounting knowledge, auditing experience",
    languages: "Bulgarian, English, Dutch (advantage)",
    contactMail: "lschroot@bgstart.nl",
    website: "https://www.bgstart.nl",
  },
  {
    logo: "https://www.pwc.bg/etc.clientlibs/pwc/clientlibs/rebrand-clientlibs/components-colors/resources/images/slim-header-v2/PwC-logo.svg",
    company: "PwC Bulgaria",
    specialty: "Junior Consultant in Audit & Finance",
    location: "Sofia, Bulgaria",
    label: "Bulgarian",
    duration: "Full-time",
    description:
      "Perform financial analysis and data collection, including reviewing financial statements and drafting recommendations for improvements. Develop skills in strategic thinking by assisting clients in aligning their financial operations with their business objectives.",
    bonuses:
      "Gain valuable experience and expand your professional network by working with diverse clients across various industries.",
    requirements:
      "A solid understanding of accounting principles and practices, Previous experience in auditing or a strong interest in developing auditing skills.",
    languages: "Bulgarian, English",
    contactMail: "bg_pwc@pwc.com",
    website:
      "https://jobs-cee.pwc.com/ce/en/job/589706WD/Junior-Consultant-in-Audit-Finance",
  },
  {
    logo: "",
    company: "MASTER OOD",
    specialty: "Engineering and Mechanical",
    location: "Bulgaria, Ruse",
    label: "Bulgarian",
    duration: "1-3 months",
    description: "Engineering and mechanical work in a workshop",
    bonuses: "Hands-on experience",
    requirements: "Bachelor's/Master's in Mechanical Engineering",
    languages: "Bulgarian",
    contactMail: "svetlozar.popov@master-bg.com",
    website: "https://www.master-bg.com",
  },
  {
    logo: "/assets/images/brand/brand-04.png",
    company: "Study Buddy Ltd.",
    specialty: "Marketing, Social Media",
    location: "Remote",
    label: "International & Remote",
    duration: "2-3 months",
    description: `We are looking for interns to manage our Instagram and TikTok. Candidates should be outgoing, communicative, and comfortable producing video content.`,
    bonuses: "Networking & exposure",
    requirements: "Marketing, PR, or related background",
    languages: "English, Bulgarian, German (plus)",
    contactMail: "marika@studybuddy.bg",
    website: "https://studybuddy.bg",
  },
  {
    logo: "/assets/images/brand/brand-06.png",
    logoClass: "splash-li",
    company: "Cool Travel Bulgaria",
    specialty: "Marketing, Management, Research",
    location: "Hybrid | Bulgaria, Sofia, Plovdiv, Varna, Burgas",
    label: "Bulgarian",
    duration: "TBD",
    description:
      "Internships available in various fields, with potential full-time opportunities. Contact Stefan Popov at popov@cooltravel.bg",
    bonuses: "Paid internship",
    requirements: "Strong research & marketing skills",
    languages: "Bulgarian, English",
    contactMail: "popov@cooltravel.bg",
    website: "https://www.cooltravel.bg",
  },
  {
    logo: "https://substackcdn.com/image/fetch/w_264,c_limit,f_webp,q_auto:best,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F196bf711-6a0e-4e4d-bef8-6d389e8b8fa3_1280x1280.png",
    company: "Groningen Mail",
    specialty: "Content Creation, PR, Marketing",
    location: "Remote",
    label: "International & Remote",
    duration: "Various (some unlimited)",
    description:
      "Contribute content and assist operations for one of the top English news sources in Groningen.",
    bonuses: "Networking & coaching",
    requirements: "Relevant experience preferred",
    languages: "English",
    contactMail: "hello@groningenmail.com",
    website: "https://www.groningenmail.com",
  },
  {
    logo: "https://www.domakin.nl/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-2.2290d784.png&w=1920&q=75",
    company: "Domakin",
    specialty: "Real Estate, Digital Marketing",
    location: "On-site, Hybrid, Remote | Netherlands",
    label: "International & Remote",
    duration: "4-10 months",
    description:
      "Student-run company helping navigate the Dutch real estate market. Join us for hands-on experience.",
    bonuses: "Mentoring & flexible schedule",
    requirements: "Availability on weekdays",
    languages: "English",
    contactMail: "domakin.nl@gmail.com",
    website: "https://www.domakin.nl",
  },
  {
    logo: "https://careers.silverstar.bg/wp-content/uploads/2024/03/channels4_profile.jpg.webp",
    company: "Silver Star",
    specialty: "Marketing, Sales, Engineering",
    location: "On-site | Bulgaria, Plovdiv",
    label: "Bulgarian",
    duration: "Varies",
    description: "Internships with career growth potential at Silver Star.",
    bonuses: "Paid internship",
    requirements: "Field-related skills preferred",
    languages: "Bulgarian, English",
    contactMail: "",
    website: "https://careers.silverstar.bg/all-positions/",
  },
  {
    logo: "https://southwesternadvantage.com/wp-content/uploads/2022/08/SWA-logo.svg",
    company: "Southwestern Advantage",
    specialty: "Management, Sales, Communication",
    location: "On-site | USA",
    label: "International & Remote",
    duration: "4-6 months",
    description:
      "Summer work & travel program for students, providing sales, leadership, and entrepreneurial experience.",
    bonuses: "Career growth & travel",
    requirements: "Full-time student, fluent English",
    languages: "English",
    contactMail: "angelinaivanova.swa@gmail.com",
    website: "https://southwesternadvantage.com",
  },
  {
    logo: "https://www.cargotec.com/Static/img/cargotec-logo.svg",
    company: "Cargotec Bulgaria",
    specialty: "Finance, HR, Procurement",
    location: "Hybrid | Bulgaria, Sofia",
    label: "Bulgarian",
    duration: "4-6 months",
    description:
      "Year-long internship program in Finance, HR, and Procurement at Cargotec Bulgaria.",
    bonuses: "Health insurance & mentoring",
    requirements: "University student, 2 days on-site",
    languages: "English",
    contactMail: "antoniya.ivanova@hiab.com",
    website:
      "https://jobs.cargotec.com/search/?createNewAlert=false&q=&locationsearch=bulgaria&optionsFacetsDD_brand=&optionsFacetsDD_facility=&optionsFacetsDD_country=&optionsFacetsDD_city=",
  },
  {
    logo: "https://nikiaviation.com/wp-content/uploads/2020/09/logo_niki-rotor-aviation1_NEW_text-krivi-1.png",
    company: "NIKI Rotor Aviation",
    specialty: "Aviation",
    location: "On-site | Bulgaria, Pravets",
    label: "Bulgarian",
    duration: "4-6 months",
    description:
      "Internship opportunities at Bulgaria’s first and only gyrocopter manufacturer.",
    bonuses: "Paid internship",
    requirements: "Technical knowledge preferred",
    languages: "Bulgarian, English",
    contactMail: "info@nikiaviation.com",
    website: "https://nikiaviation.com/",
  },
];

export const GOOGLE_FORM_APPLICATION = (
  company = "",
  specialty = "",
  user = {
    name: "",
    surname: "",
    region: "",
    email: "",
    phone: "",
  }
) =>
  `https://docs.google.com/forms/d/e/1FAIpQLSdtA4BKxFyAr6veADoN-F6xiNZnJlUOtIq9_0kAnanzR8DzcA/viewform?usp=pp_url&entry.1352553752=${company}&entry.1469541182=${specialty}&entry.1671432341=${user.name}&entry.1629488041=${user.surname}&entry.1526397372=${user.email}&entry.1093414160=${user.email}&entry.747940554=${user.region}&entry.1203011269=${user.phone}`;
