export const INTERNSHIPS_LIST = [
  {
    logo: "https://www.bgstart.nl/bg/wp-content/uploads/2019/01/favicon.png",
    company: "BG Start",
    specialty: "Accountancy",
    location: "Amsterdam (Hybrid)",
    duration: "Flexible",
    description: `Assisting with data entry, processing, and recording transactions. Financial Reporting: Helping prepare financial reports, budgets, and invoices. Administrative Support: Assisting with audits, fact-checking, and maintaining financial documents.`,
    bonuses: "Experience & networking",
    requirements: "Accounting knowledge, auditing experience",
    languages: "Bulgarian, English, Dutch (advantage)",
    contactMail: "lschroot@bgstart.nl",
    website: "https://www.bgstart.nl",
  },
  {
    logo: "",
    company: "MASTER OOD",
    specialty: "Engineering and Mechanical",
    location: "Bulgaria, Ruse",
    duration: "1-3 months",
    description: "Engineering and mechanical work in a workshop",
    bonuses: "Hands-on experience",
    requirements: "Bachelor's/Master's in Mechanical Engineering",
    languages: "Bulgarian",
    contactMail: "svetlozar.popov@master-bg.com",
    website: "https://www.master-bg.com",
  },
  {
    logo: "/assets/images/brand/brand-04.png",
    company: "Study Buddy Ltd.",
    specialty: "Marketing, Social Media",
    location: "Remote",
    duration: "2-3 months",
    description: `We are looking for interns to manage our Instagram and TikTok. Candidates should be outgoing, communicative, and comfortable producing video content.`,
    bonuses: "Networking & exposure",
    requirements: "Marketing, PR, or related background",
    languages: "English, Bulgarian, German (plus)",
    contactMail: "marika@studybuddy.bg",
    website: "https://studybuddy.bg",
  },
  {
    logo: "/assets/images/brand/brand-06.png",
    logoClass: "splash-li",
    company: "Cool Travel Bulgaria",
    specialty: "Marketing, Management, Research",
    location: "Hybrid | Bulgaria, Sofia, Plovdiv, Varna, Burgas",
    duration: "TBD",
    description:
      "Internships available in various fields, with potential full-time opportunities. Contact Stefan Popov at popov@cooltravel.bg",
    bonuses: "Paid internship",
    requirements: "Strong research & marketing skills",
    languages: "Bulgarian, English",
    contactMail: "popov@cooltravel.bg",
    website: "https://www.cooltravel.bg",
  },
  {
    logo: "https://substackcdn.com/image/fetch/w_264,c_limit,f_webp,q_auto:best,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F196bf711-6a0e-4e4d-bef8-6d389e8b8fa3_1280x1280.png",
    company: "Groningen Mail",
    specialty: "Content Creation, PR, Marketing",
    location: "Remote",
    duration: "Various (some unlimited)",
    description:
      "Contribute content and assist operations for one of the top English news sources in Groningen.",
    bonuses: "Networking & coaching",
    requirements: "Relevant experience preferred",
    languages: "English",
    contactMail: "hello@groningenmail.com",
    website: "https://www.groningenmail.com",
  },
  {
    logo: "https://www.domakin.nl/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-2.2290d784.png&w=1920&q=75",
    company: "Domakin",
    specialty: "Real Estate, Digital Marketing",
    location: "On-site, Hybrid, Remote | Netherlands",
    duration: "4-10 months",
    description:
      "Student-run company helping navigate the Dutch real estate market. Join us for hands-on experience.",
    bonuses: "Mentoring & flexible schedule",
    requirements: "Availability on weekdays",
    languages: "English",
    contactMail: "domakin.nl@gmail.com",
    website: "https://www.domakin.nl",
  },
  {
    logo: "https://careers.silverstar.bg/wp-content/uploads/2024/03/channels4_profile.jpg.webp",
    company: "Silver Star",
    specialty: "Marketing, Sales, Engineering",
    location: "On-site | Bulgaria, Plovdiv",
    duration: "Varies",
    description: "Internships with career growth potential at Silver Star.",
    bonuses: "Paid internship",
    requirements: "Field-related skills preferred",
    languages: "Bulgarian, English",
    contactMail: "",
    website: "https://careers.silverstar.bg/all-positions/",
  },
  {
    logo: "https://southwesternadvantage.com/wp-content/uploads/2022/08/SWA-logo.svg",
    company: "Southwestern Advantage",
    specialty: "Management, Sales, Communication",
    location: "On-site | USA",
    duration: "4-6 months",
    description:
      "Summer work & travel program for students, providing sales, leadership, and entrepreneurial experience.",
    bonuses: "Career growth & travel",
    requirements: "Full-time student, fluent English",
    languages: "English",
    contactMail: "angelinaivanova.swa@gmail.com",
    website: "https://southwesternadvantage.com",
  },
  {
    logo: "https://www.cargotec.com/Static/img/cargotec-logo.svg",
    company: "Cargotec Bulgaria",
    specialty: "Finance, HR, Procurement",
    location: "Hybrid | Bulgaria, Sofia",
    duration: "4-6 months",
    description:
      "Year-long internship program in Finance, HR, and Procurement at Cargotec Bulgaria.",
    bonuses: "Health insurance & mentoring",
    requirements: "University student, 2 days on-site",
    languages: "English",
    contactMail: "antoniya.ivanova@hiab.com",
    website:
      "https://jobs.cargotec.com/search/?createNewAlert=false&q=&locationsearch=bulgaria&optionsFacetsDD_brand=&optionsFacetsDD_facility=&optionsFacetsDD_country=&optionsFacetsDD_city=",
  },
  {
    logo: "https://nikiaviation.com/wp-content/uploads/2020/09/logo_niki-rotor-aviation1_NEW_text-krivi-1.png",
    company: "NIKI Rotor Aviation",
    specialty: "Aviation",
    location: "On-site | Bulgaria, Pravets",
    duration: "4-6 months",
    description:
      "Internship opportunities at Bulgaria’s first and only gyrocopter manufacturer.",
    bonuses: "Paid internship",
    requirements: "Technical knowledge preferred",
    languages: "Bulgarian, English",
    contactMail: "info@nikiaviation.com",
    website: "https://nikiaviation.com/",
  },
];
