import { BGSNL_INTERNSHIP_MAIL_SUBJECT } from "./common";

export const INTERNSHIPS_LIST = [
  {
    logo: "https://www.bgstart.nl/bg/wp-content/uploads/2019/01/favicon.png",
    company: "BG Start",
    specialty: "Accountancy",
    location: "Amsterdam (Hybrid)",
    duration: "Flexible",
    description: `Assisting with data entry, processing, and recording transactions. Financial Reporting: Helping prepare financial reports, budgets, and invoices. Administrative Support: Assisting with audits, fact-checking, and maintaining financial documents.`,
    bonuses: [
      "Networking",
      "exposure",
      "experience",
      "opportunity for paid job",
    ],
    requirements: [
      "expertise or some knowledge in Accountancy, Economics ",
      "languages - Bulgarian, English, Dutch (is considered advantage).",
    ],
    contactMail: `lschroot@bgstart.nl`,
    website: "www.bgstart.nl",
  },
  {
    logo: "",
    company: "MASTER OOD",
    specialty: "Engineering and mechanical",
    location: "Bulgaria, Ruse",
    duration: "1-3 months",
    description: `Engineering and mechanical work in a workshop`,
    bonuses: ["experience"],
    requirements: [
      "Bachelor or Masters in Mechanical Engineering",
      "languages - Bulgarian.",
    ],
    contactMail: `svetlozar.popov@master-bg.com`,
    website: "www.master-bg.com",
  },
  {
    logo: "/assets/images/brand/brand-04.png",
    company: "Study Buddy Ltd.",
    specialty: "Marketing, social media",
    location: "Remote",
    duration: "2-3 months",
    description: `We are looking for interns to take over our social media channels - Instagram and Tik Tok. Our little cozy and absolutely non-traditional company could offer positions to two interns that would be handling these channels. We are looking for outgoing and communicative slayish super roca fella Gen Z-s who wouldn't be afraid to be in front of the camera to produce their own reels and TikTok videos, follow all trends on these social platforms and create content that will enhance our vision (make the world a better place by delivering content about studies abroad). Contact Marika Vasileva, marika@studybuddy.bg for more`,
    bonuses: ["Networking", "exposure", "experience"],
    requirements: [
      "Bachelor or Master degree",
      " preferably - degrees in marketing, business, communication, PR, media, etc.",
      "languages - English, Bulgarian.German language is a plus.",
    ],
    contactMail: `marika@studybuddy.bg`,
    website: "https://studybuddy.bg",
  },
  {
    logo: "/assets/images/brand/brand-06.png",
    logoClass: "splash-li",
    company: "Cool Travel Bulgaria",
    specialty: "Marketing, Management, Customer care, Research ",
    location: "Hybrid | Bulgaria, Sofia, Plovdov, Varna, Burgas",
    duration: "TBD",
    description:
      "Offered internships in different fields with different perspectives and the chance to earn the spot on the Cool Travel team. To candidate check the website or contact Stefan Popov at popov@cooltravel.bg",
    bonuses: ["Paid"],
    requirements: ["Bulgarian and English language skills"],
    contactMail: `popov@cooltravel.bg`,
    website: "https://www.cooltravel.bg",
  },
  {
    logo: "https://substackcdn.com/image/fetch/w_264,c_limit,f_webp,q_auto:best,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F196bf711-6a0e-4e4d-bef8-6d389e8b8fa3_1280x1280.png",
    company: "Groningen Mail",
    specialty: "Content Creation, Writing, PR, Marketing",
    location: "Remote",
    duration: "various (some with no limit)",
    description:
      "Be a Contributor - Contribute content, articles or operational help to one of the most prominent English news sources in Groningen. For more info check the website or contact Arian Adeli, hello@groningenmail.com",
    bonuses: [
      "Networking",
      "exposure",
      "events",
      "experience",
      "coaching",
      "company activities",
    ],
    requirements: [
      "Fluent in English",
      "Relevant experience is preferred but not required",
    ],
    contactMail: `hello@groningenmail.com`,
    website: "https://www.groningenmail.com",
  },
  {
    logo: "https://www.domakin.nl/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-2.2290d784.png&w=1920&q=75",
    company: "Domakin",
    specialty: "Real Estate, Digital Marketing",
    location: "On-site, hybrid and remote | Netherlands",
    duration: "4-10 months",
    description:
      "Domakin is a student to student company with the goal of helping in the competitive real estate market in the Netherlands. The team is always expanding and giving opportunity to young talents to extend their skill set and gain some field experience. If you are interested in the start-up, write down an email to book an online or on-site meeting with the board from the contactMail below.",
    bonuses: ["Mentoring", "Flexible schedule", "Networking"],
    requirements: [
      "Availability during week days",
      "Fluent English",
      "Ability to work onsite (applies for Real Estate Agent only)",
    ],
    contactMail: `domakin.nl@gmail.com`,
    website: "https://www.domakin.nl",
  },
  {
    logo: "https://careers.silverstar.bg/wp-content/uploads/2024/03/channels4_profile.jpg.webp",
    company: "Silver Star",
    specialty: "Marketing, Sales, Mechanical Engineering",
    location: "On-site | Bulgaria, Plovdiv",
    duration: "variates",
    description:
      "Offered internships in different fields with different perspectives and the chance to earn the spot on the Silver Star team",
    bonuses: ["Paid"],
    requirements: [],
    contactMail: "",
    website: "https://careers.silverstar.bg/all-positions/",
  },
  {
    logo: "https://southwesternadvantage.com/wp-content/uploads/2022/08/SWA-logo.svg",
    company: "Southwestern Advantage",
    specialty: "Management, Communication, Sales",
    location: "On-site | USA",
    duration: "4-6 months",
    description:
      "Southwestern Advantage offers a unique award-winning student work and travel summer program! It gives university students a way to afford their degrees, gain work ex-perience, entrepreneurial skills, and build character needed to achieve their goals in life.",
    bonuses: [],
    requirements: ["Fluent English", "Be a full-time student"],
    contactMail: `angelinaivanova.swa@gmail.com`,
    website: "https://southwesternadvantage.com",
  },
  {
    logo: "https://www.cargotec.com/Static/img/cargotec-logo.svg",
    company: "Cargotec Bulgaria",
    specialty: "Finance, HR, Procurement",
    location: "Hybrid | Bulgaria, Sofia",
    duration: "4-6 months",
    description:
      'In 2019, Cargotec Bulgaria launched its year-long internship program for students, which continues to welcome interns in the "Finance," "Human Resources," and "Indirect Procurement" departments.',
    bonuses: [
      "Additional health insurance",
      "Paid leave",
      "Food vouchers",
      "Mentoring",
    ],
    requirements: [
      "Ongoing or obtained university degree",
      "Fluent English",
      "Ability to work onsite (approx. 2 timer per week)",
    ],
    contactMail: `antoniya.ivanova@hiab.com`,
    website:
      "https://jobs.cargotec.com/search/?createNewAlert=false&q=&locationsearch=bulgaria&optionsFacetsDD_brand=&optionsFacetsDD_facility=&optionsFacetsDD_country=&optionsFacetsDD_city=",
  },
  {
    logo: "https://nikiaviation.com/wp-content/uploads/2020/09/logo_niki-rotor-aviation1_NEW_text-krivi-1.png",
    company: "NIKI Rotor Aviation",
    specialty: "Aviation",
    location: "On-site | Bulgaria, Pravets",
    duration: "4-6 months",
    description:
      "We offer internship opportunities at NIKI Rotor Aviation - the first and only Bulgarian manufacturer of gyrocopters.",
    bonuses: ["Paid"],
    requirements: [],
    contactMail: `info@nikiaviation.com`,
    website: "https://nikiaviation.com/",
  },
];