// Generated by scripts/export-past-events-from-tickets.js.
// Public event summaries only; attendee and payment data are intentionally excluded.
import archive from "./past-events-archive.json";

export const PAST_EVENTS_ARCHIVE_GENERATED_AT = archive.generatedAt;
export const PAST_EVENTS_ARCHIVE_STATS = archive.stats;
export const PAST_EVENTS_ARCHIVE = archive.events;
